# Generated by Django 3.2.16 on 2023-01-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_id', models.IntegerField(unique=True)),
                ('text', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_takes', to='quickstart.user')),
                ('remixes', models.ManyToManyField(blank=True, related_name='_quickstart_take_remixes_+', through='quickstart.Remix', to='quickstart.Take')),
                ('sources', models.ManyToManyField(blank=True, related_name='_quickstart_take_sources_+', through='quickstart.Remix', to='quickstart.Take')),
            ],
        ),
        migrations.AddField(
            model_name='remix',
            name='mix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remix_mix', to='quickstart.take'),
        ),
        migrations.AddField(
            model_name='remix',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remix_source', to='quickstart.take'),
        ),
    ]
