# Generated by Django 3.2.17 on 2023-02-06 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20230206_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take',
            name='placeholders',
            field=models.ManyToManyField(blank=True, related_name='template_take', through='quickstart.TemplatePhrase', to='quickstart.Phrase'),
        ),
        migrations.AlterField(
            model_name='templatephrase',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.phrase'),
        ),
        migrations.AlterField(
            model_name='templatephrase',
            name='template_take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.take'),
        ),
        migrations.CreateModel(
            name='SubstitutionPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.phrase')),
                ('substitution_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.take')),
            ],
        ),
        migrations.AddField(
            model_name='take',
            name='substitutions',
            field=models.ManyToManyField(blank=True, through='quickstart.SubstitutionPhrase', to='quickstart.Phrase'),
        ),
    ]
