# Generated by Django 3.2.17 on 2023-02-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20230206_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take',
            name='substitutions',
            field=models.ManyToManyField(blank=True, related_name='substitution_take', through='quickstart.SubstitutionPhrase', to='quickstart.Phrase'),
        ),
    ]
