# Generated by Django 4.1.7 on 2023-02-18 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_alter_take_substitutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='templates',
            field=models.ManyToManyField(blank=True, through='quickstart.TemplatePhrase', to='quickstart.take'),
        ),
        migrations.AddField(
            model_name='take',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 3, 13, 43, 673084, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='take',
            name='remixes',
            field=models.ManyToManyField(blank=True, through='quickstart.Remix', to='quickstart.take'),
        ),
        migrations.AlterField(
            model_name='take',
            name='sources',
            field=models.ManyToManyField(blank=True, through='quickstart.Remix', to='quickstart.take'),
        ),
    ]
